export { default as lockIcon } from './lockIcon.svg';
export { default as menuIcon } from './menuIcon.svg';
export { default as closeIcon } from './closeIcon.svg';
export { default as logoWhite } from './whiteLogo.svg';
export { default as logoBlue } from './blueLogo.svg';
export { default as welcomeBackgroundImage } from './Background.svg';
export { default as projectGradientBackgroundImage } from './projectGradientBackgroundImage.png';
export { default as cubesImage } from './cube.svg';
export { default as DiagramLogo } from './Diagram.svg';
export { default as nftImage } from './nftImage.svg';
export { default as humanImage } from './humanImage.svg';
export { default as joystickImage } from './bluejoystick.svg';
export { default as joystick2Image } from './joystick.svg';
export { default as btcImage } from './btcImage.svg';
export { default as keyImage } from './keyImage.svg';
export { default as startupBackgroundImage } from './startupBackgroundImage.png';
export { default as twitterIcon } from './twitterIcon.svg';
export { default as instagram } from './instagram.svg';
export { default as ball } from './ball.svg';
export { default as facebook } from './facebook.svg';
export { default as github } from './github.svg';
export { default as btcIcon } from './bitcoinLogo.svg';
export { default as arrowRightIcon } from './arrowRightIcon.svg';

export { default as step1Icon } from './step1.svg';
export { default as step2Icon } from './step2.svg';
export { default as step3Icon } from './step3.svg';
export { default as step4Icon } from './step4.svg';
export { default as infoIcon } from './info.svg';

export { default as MizarLogo } from './mizarLogo.svg';

export { default as SkillLogo } from './skillLogo.svg';
export { default as wilderLogo } from './wilderWorldLogo.svg';
export { default as seorLogo } from './SeorLogo.svg';
export { default as clockIcon } from './clockIcon.svg';
export { default as socialIcon } from './socialIcon.svg';
export { default as websiteIcon } from './websiteIcon.svg';
export { default as NFTHumanImage } from './NFTHumanImage.svg';
export { default as arrowIcon } from './arrow.svg';
export { default as BlockChainLogo } from './blockchainLogo.svg';
export { default as BallImage } from './ball.png';
export { default as AvatarImage } from './avatar.svg';
export { default as AcmeLogo } from './ACMEImage.svg';
export { default as SpartaLogo } from './SpartaImage.svg';
export { default as TIER1Logo } from './t1x2.png';
export { default as TIER2Logo } from './t2x2.png';
export { default as TIER4Logo } from './t4x2.png';
export { default as TIER3Logo } from './t3x2.png';
export { default as TIER1Small } from './Union1.svg';
export { default as TIER2Small } from './Union2.svg';
export { default as TIER3Small } from './Union3.svg';
export { default as TIER4Small } from './Union4.svg';
export { default as LogoAngePasst } from './Union.svg';

export { default as NFTtier1 } from './tier-1 (1).png';
export { default as NFTtier2 } from './tier-2 (1).png';
export { default as NFTtier3 } from './tier-3 (1).png';
export { default as NFTtier4 } from './tier-4 (1).png';
export { default as rareNfts } from './rare-nfts.png';
export { default as agreement } from './agreement.png';
export { default as fail } from './fail.png';
export { default as finalogo } from './fina.png';
export { default as finaCard } from './finaCard.png';
export { default as checkmark } from './checkmark.svg';
export { default as burgerMenu } from './burgerMenu.svg';
export { default as leftArrow } from './leftArrow.png';
export { default as checked } from './checked.png';
export { default as successParticipation } from './successParticipation.png';
export { default as successUpgrade } from './successUpgrade.png';
